use std::str::FromStr;
use crate::ast::{Expr, OpCode};

grammar;

pub Expr : Box<Expr> = {
    Expr ExprOp Factor => Box::new(Expr::Op(<>)),
    Factor
};

ExprOp : OpCode = {
    "+" => OpCode::Add,
    "-" => OpCode::Sub,
};

Factor : Box<Expr> = {
    Factor FactorOp Term => Box::new(Expr::Op(<>)),
    Term,
};

FactorOp : OpCode = {
    "*" => OpCode::Mul,
    "/" => OpCode::Div,
};

Term : Box<Expr> = {
    Num => Box::new(Expr::Number(<>)),
    "(" <Expr> ")",
};

Num : i32 = {
    r"[0-9]+" => i32::from_str(<>).unwrap()
};
